// Utility used to generate the EnvConstants.cs file from a .env file.
//
// Build it by running `dotnet build -o ../bin` from the GenerateEnvConstants directory.

using System;
using System.IO;
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.WriteLine("Usage: dotnet exec GenerateEnvConstants.dll <inputFile> <outputFile>");
            return;
        }

        var inputFile = Path.GetFullPath(args[0]);
        var outputFile = Path.GetFullPath(args[1]);

        if (!File.Exists(inputFile))
        {
            Console.WriteLine($"Error: Input file '{inputFile}' does not exist.");
            return;
        }

        var constants = new List<string>();

        foreach (var line in File.ReadAllLines(inputFile))
        {
            var trimmedLine = line.Trim();
            if (string.IsNullOrWhiteSpace(trimmedLine) || trimmedLine.StartsWith("#"))
                continue;

            var parts = trimmedLine.Split('=', 2);
            if (parts.Length == 2)
            {
                var key = parts[0].Trim();
                var value = parts[1].Trim().Trim('"');
                constants.Add($"public const string {key} = \"{value}\";");
            }
        }

        var output = $@"
/***   GENERATED FILE - DO NOT EDIT   ***/

// This file is generated by tools/bin/GenerateEnvConstants, using .env as input.
// Do not edit this file directly. Instead, edit .env and regenerate this file.

namespace Generated
{{
    public static class EnvConstants
    {{
        {string.Join(Environment.NewLine + "        ", constants)}
    }}
}}
";
        Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);
        File.WriteAllText(outputFile, output);
        Console.WriteLine($"Constants generated in {outputFile}");
    }
}
