name: flutter_quickstart
description: "Demonstrates how to use the ditto_live plugin."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  ditto_live: ^5.0.0-experimental-flutter.5
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
