#!/usr/bin/awk -f

# This script is used to generate the "env.h" file that contains C++ definitions
# corresponding to the values in the ".env" file at the repository root.
#
# Run it like this, from the taskscpp directory:
#
#  awk -f scripts/generate_env.awk ../../.env > src/env.h

BEGIN {
  print "#ifndef DITTO_QUICKSTART_ENV_H"
  print "#define DITTO_QUICKSTART_ENV_H"
  print "\n/***   GENERATED FILE - DO NOT EDIT   ***/"
  print "\n// This file is generated by taskscpp/scripts/generate_env.awk, using .env as input."
  print "// Do not edit this file directly--instead edit .env and regenerate this file.\n"
}

# Match lines of the form TOKEN_NAME = "token_value" from the input file
/^[[:space:]]*[A-Z0-9_]+[[:space:]]+=[[:space:]]+"[^"]+"*/ {
  print "#define " $1 " " $3
  next
}

# Match lines of the form TOKEN_NAME = token_value from the input file
/^[[:space:]]*[A-Z0-9_]+[[:space:]]+=[[:space:]]+*/ {
  print "#define " $1 " \"" $2 "\""
  next
}

END {
  print "\n#endif // DITTO_QUICKSTART_ENV_H"
}
