name: C++ TUI Secondary CI
on:
  pull_request:
    branches: [main]
    paths:
      - 'cpp-tui/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DITTO_SDK_VERSION: "4.12.0"

jobs:
  secondary-test:
    name: Secondary C++ TUI Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "DITTO_APP_ID=${{ secrets.DITTO_APP_ID }}" > .env
          echo "DITTO_PLAYGROUND_TOKEN=${{ secrets.DITTO_PLAYGROUND_TOKEN }}" >> .env
          echo "DITTO_AUTH_URL=${{ secrets.DITTO_AUTH_URL }}" >> .env
          echo "DITTO_WEBSOCKET_URL=${{ secrets.DITTO_WEBSOCKET_URL }}" >> .env
      
      - name: Insert test document into Ditto Cloud
        run: |
          DOC_ID="cpp_secondary_test_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
          
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -H 'Content-type: application/json' \
            -H "Authorization: Bearer ${{ secrets.DITTO_API_KEY }}" \
            -d "{
              \"statement\": \"INSERT INTO tasks DOCUMENTS (:newTask) ON ID CONFLICT DO UPDATE\",
              \"args\": {
                \"newTask\": {
                  \"_id\": \"${DOC_ID}\",
                  \"title\": \"C++ Secondary Test Task ${GITHUB_RUN_ID}\",
                  \"done\": false,
                  \"deleted\": false
                }
              }
            }" \
          "https://${{ secrets.DITTO_API_URL }}/api/v4/store/execute")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          
          if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ]; then
            echo "✓ Successfully inserted secondary test document: ${DOC_ID}"
            echo "SECONDARY_TEST_DOC_ID=${DOC_ID}" >> $GITHUB_ENV
          else
            echo "❌ Failed to insert secondary test document"
            exit 1
          fi
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang clang-format build-essential
      
      - name: Run linter
        working-directory: cpp-tui/taskscpp
        run: |
          echo "🎨 Running clang-format check..."
          make format
          # Check if files were modified
          if ! git diff --exit-code; then
            echo "❌ Code style issues found. Run 'make format' to fix."
            exit 1
          fi
          echo "✅ Code style check passed"

      - name: Download and setup Ditto C++ SDK
        working-directory: cpp-tui/taskscpp
        run: |
          
          echo "📥 Downloading real Ditto C++ SDK v${{ env.DITTO_SDK_VERSION }}..."
          curl -O https://software.ditto.live/cpp-linux-x86_64/Ditto/${{ env.DITTO_SDK_VERSION }}/dist/Ditto.tar.gz
          tar xvfz Ditto.tar.gz
          cp Ditto.h sdk/
          cp libditto.a sdk/
          
          # Generate env.h
          awk -f scripts/generate_env.awk ../../.env > src/env.h
          
          # Build with real SDK
          make build
          
          echo "✅ C++ TUI app built with real Ditto SDK for secondary testing"
      
      - name: Run integration tests
        working-directory: cpp-tui/taskscpp
        env:
          SECONDARY_TEST_DOC_ID: ${{ env.SECONDARY_TEST_DOC_ID }}
        run: |
          echo "🧪 Running integration tests with document: ${SECONDARY_TEST_DOC_ID}"
          echo "🌐 This will connect to REAL Ditto Cloud and verify document syncs"
          
          # Build and run integration test with REAL Ditto SDK
          g++ -std=c++17 -I./src -I./sdk -I./third_party/cxxopts/include \
            tests/integration_test.cpp \
            src/task.cpp src/tasks_peer.cpp src/tasks_log.cpp \
            -L./sdk -lditto -ldl -lrt -pthread \
            -o build/integration_test
          
          # Run test that will verify the document syncs via real Ditto SDK
          ./build/integration_test
          
          echo "✅ Secondary integration tests completed successfully"