name: test-flutter-github-actions

on:
  pull_request:
    branches: 
      - "main"
    
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with: 
          channel: stable
          flutter-version: "3.32.8"
      
      - name: Run tests
        env:
          DITTO_APP_ID: ${{ secrets.DITTO_APP_ID }}
          DITTO_PLAYGROUND_TOKEN: ${{ secrets.DITTO_PLAYGROUND_TOKEN }}
          DITTO_WEBSOCKET_URL: ${{ secrets.DITTO_WEBSOCKET_URL }}
          DITTO_AUTH_URL: ${{ secrets.DITTO_AUTH_URL }}
          DITTO_API_URL: ${{ secrets.DITTO_API_URL }}
          DITTO_API_KEY: ${{ secrets.DITTO_API_KEY }}
        run: |
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install \
            clang cmake git \
            ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            libstdc++-12-dev

          sudo apt-get install -y libglu1-mesa xvfb
          
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

          cd flutter_app
          flutter pub get
          flutter test integration_test/ditto_sync_test.dart \
            --dart-define "DITTO_APP_ID=$DITTO_APP_ID" \
            --dart-define "DITTO_PLAYGROUND_TOKEN=$DITTO_PLAYGROUND_TOKEN" \
            --dart-define "DITTO_WEBSOCKET_URL=$DITTO_WEBSOCKET_URL" \
            --dart-define "DITTO_AUTH_URL=$DITTO_AUTH_URL" \
            --dart-define "DITTO_API_URL=$DITTO_API_URL" \
            --dart-define "DITTO_API_KEY=$DITTO_API_KEY" \
            -d linux
