#
# .github/workflows/pr-checks.yml
#
---
name: PR Checks

on:
  pull_request:
    branches:
      - main
      - 'sdk-*'
  push:
    branches:
      - main
      - 'sdk-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    name: Rust Quickstart
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy

      - name: Run clippy
        run: |
          cd rust-tui
          cargo clippy

      - name: Build project
        run: |
          cd rust-tui
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            export RUSTFLAGS="-C prefer-dynamic"
          fi
          cargo build

  js-web:
    name: JavaScript Web Lint (ubuntu-24.04)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: javascript-web
        run: npm ci

      - name: Run linting
        working-directory: javascript-web
        run: npm run lint

  js-node:
    name: JavaScript TUI Lint (ubuntu-24.04)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: javascript-tui
        run: npm ci

      - name: Run linting and tests
        working-directory: javascript-tui
        run: npm run test
