#
# .github/workflows/pr-checks.yml
#
---
name: PR Checks

on:
  pull_request:
    branches:
      - main
      - 'sdk-*'
  push:
    branches:
      - main
      - 'sdk-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: Android (ubuntu-24.04)

    # https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update && sudo apt install just
          just --version
          just tools


  js-web:
    name: JavaScript Web Lint (ubuntu-24.04)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: javascript-web
        run: npm ci

      - name: Run linting
        working-directory: javascript-web
        run: npm run lint

  js-node:
    name: JavaScript TUI Lint (ubuntu-24.04)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: javascript-tui
        run: npm ci

      - name: Run linting and tests
        working-directory: javascript-tui
        run: npm run test


  flutter:
    name: Flutter (ubuntu-24.04)
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Create .env file
        run: |
          echo "DITTO_APP_ID=${{ secrets.DITTO_APP_ID }}" > flutter_app/.env
          echo "DITTO_PLAYGROUND_TOKEN=${{ secrets.DITTO_PLAYGROUND_TOKEN }}" >> flutter_app/.env
          echo "DITTO_AUTH_URL=${{ secrets.DITTO_AUTH_URL }}" >> flutter_app/.env
          echo "DITTO_WEBSOCKET_URL=${{ secrets.DITTO_WEBSOCKET_URL }}" >> flutter_app/.env

      - name: Create local.properties
        working-directory: flutter_app/android
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > local.properties
          echo "flutter.buildMode=debug" >> local.properties
          echo "flutter.versionName=1.0.0" >> local.properties
          echo "flutter.versionCode=1" >> local.properties

      - name: Get dependencies
        working-directory: flutter_app
        run: flutter pub get

      - name: Analyze project
        working-directory: flutter_app
        run: flutter analyze

      - name: Run tests
        working-directory: flutter_app
        run: flutter test

      - name: Build APK
        working-directory: flutter_app
        run: flutter build apk --debug

      - name: Build Web
        working-directory: flutter_app
        run: flutter build web
