name: React Native Expo CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'react-native-expo/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'react-native-expo/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: react-native-expo/yarn.lock
    
    - name: Install dependencies
      working-directory: react-native-expo
      run: yarn install
    
    - name: Run linting
      working-directory: react-native-expo
      run: yarn lint

  build-android:
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: react-native-expo/yarn.lock
    
    - name: Install dependencies
      working-directory: react-native-expo
      run: yarn install
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          react-native-expo/android/.gradle
        key: gradle-expo-${{ runner.os }}-${{ hashFiles('react-native-expo/android/gradle/wrapper/gradle-wrapper.properties', 'react-native-expo/android/**/*.gradle*') }}
        restore-keys: |
          gradle-expo-${{ runner.os }}-
    
    - name: Prebuild Android project
      working-directory: react-native-expo
      run: npx expo prebuild --platform android
    
    - name: Build Android
      working-directory: react-native-expo
      run: yarn build:android

  build-ios:
    runs-on: macos-latest
    needs: lint
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: react-native-expo/yarn.lock
    
    - name: Install dependencies
      working-directory: react-native-expo
      run: yarn install
    
    - name: Cache CocoaPods dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/CocoaPods
          ~/.cocoapods
        key: cocoapods-expo-${{ runner.os }}-${{ hashFiles('react-native-expo/ios/Podfile.lock') }}
        restore-keys: |
          cocoapods-expo-${{ runner.os }}-
    
    - name: Prebuild iOS project
      working-directory: react-native-expo
      run: npx expo prebuild --platform ios
    
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app
    
    - name: Install CocoaPods
      working-directory: react-native-expo/ios
      run: pod install --repo-update
    
    - name: Build iOS
      working-directory: react-native-expo
      run: yarn build:ios