name: react-native-expo-appium-browserstack

on:
  pull_request:
    branches: [main]
    paths:
      - 'react-native-expo/**'
      - '.github/workflows/react-native-expo-appium-browserstack.yml'
      - '.github/scripts/browserstack-appium-test.py'
  push:
    branches: [main]
    paths:
      - 'react-native-expo/**'
      - '.github/workflows/react-native-expo-appium-browserstack.yml'
      - '.github/scripts/browserstack-appium-test.py'
  workflow_dispatch:

concurrency:
  group: rn-expo-android-appium-browserstack-${{ github.ref }}
  cancel-in-progress: false

jobs:
  appium-tests:
    name: Appium Android Tests (ubuntu-latest)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: react-native-expo/yarn.lock

      - name: Create .env file
        run: |
          echo "DITTO_APP_ID=${{ secrets.DITTO_APP_ID }}" > .env
          echo "DITTO_PLAYGROUND_TOKEN=${{ secrets.DITTO_PLAYGROUND_TOKEN }}" >> .env
          echo "DITTO_AUTH_URL=${{ secrets.DITTO_AUTH_URL }}" >> .env
          echo "DITTO_WEBSOCKET_URL=${{ secrets.DITTO_WEBSOCKET_URL }}" >> .env

      - name: Insert test document into Ditto Cloud
        run: |
          # Use GitHub run ID to create deterministic document ID
          DOC_ID="github_expo_appium_test_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          # Insert document using curl with correct JSON structure
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -H 'Content-type: application/json' \
            -H "Authorization: Bearer ${{ secrets.DITTO_API_KEY }}" \
            -d "{
              \"statement\": \"INSERT INTO tasks DOCUMENTS (:newTask) ON ID CONFLICT DO UPDATE\",
              \"args\": {
                \"newTask\": {
                  \"_id\": \"${DOC_ID}\",
                  \"title\": \"GitHub Expo Appium Test Task ${GITHUB_RUN_ID}\",
                  \"done\": false,
                  \"deleted\": false
                }
              }
            }" \
          "https://${{ secrets.DITTO_API_URL }}/api/v4/store/execute")
          
          # Extract HTTP status code and response body
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          # Check if insertion was successful
          if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 201 ]; then
            echo "✓ Successfully inserted test document with ID: ${DOC_ID}"
            echo "GITHUB_TEST_DOC_ID=${DOC_ID}" >> $GITHUB_ENV
          else
            echo "❌ Failed to insert document. HTTP Status: $HTTP_CODE"
            echo "Response: $BODY"
            exit 1
          fi

      - name: Install dependencies
        working-directory: react-native-expo
        run: yarn install

      - name: Run linter
        working-directory: react-native-expo
        run: yarn lint

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            react-native-expo/android/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        working-directory: react-native-expo/android
        run: chmod +x ./gradlew

      - name: Build Android APK
        working-directory: react-native-expo
        run: |
          # Build APK directly using Gradle assembleDebug task
          cd android && ./gradlew assembleDebug --no-daemon --console=plain
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      - name: Verify APK exists
        run: |
          APK_PATH="react-native-expo/android/app/build/outputs/apk/debug/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            echo "✓ APK found: $APK_PATH"
            echo "APK size: $(du -h "$APK_PATH" | cut -f1)"
          else
            echo "❌ APK not found at expected location: $APK_PATH"
            echo "Searching for APK files:"
            find react-native-expo/android -name "*.apk" -type f
            exit 1
          fi

      - name: Setup Python and install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r .github/scripts/requirements.txt

      - name: Make test script executable
        run: chmod +x .github/scripts/browserstack-appium-test.py

      - name: Execute Appium tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          DITTO_APP_ID: ${{ secrets.DITTO_APP_ID }}
          DITTO_PLAYGROUND_TOKEN: ${{ secrets.DITTO_PLAYGROUND_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_TEST_DOC_ID: ${{ env.GITHUB_TEST_DOC_ID }}
          APP_TYPE: "expo"
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python3 .github/scripts/browserstack-appium-test.py

      - name: Generate test report
        if: always()
        run: |
          echo "# React Native Expo Appium Test Report" > appium-test-report.md
          echo "" >> appium-test-report.md
          echo "## Test Configuration" >> appium-test-report.md
          echo "- **App Type**: React Native with Expo" >> appium-test-report.md
          echo "- **Test Framework**: Appium" >> appium-test-report.md
          echo "- **Platform**: BrowserStack App Automate" >> appium-test-report.md
          echo "- **GitHub Run**: #${{ github.run_number }}" >> appium-test-report.md
          echo "" >> appium-test-report.md
          echo "## Tested Devices" >> appium-test-report.md
          echo "- Google Pixel 7 (Android 13.0)" >> appium-test-report.md
          echo "" >> appium-test-report.md
          echo "## Sync Verification" >> appium-test-report.md
          echo "- **External Test Document ID**: ${GITHUB_TEST_DOC_ID:-Not generated}" >> appium-test-report.md
          echo "" >> appium-test-report.md
          echo "## Test Cases Executed" >> appium-test-report.md
          echo "1. **App Launch**: Permission handling and app startup" >> appium-test-report.md
          echo "2. **Main Screen Load**: UI element verification" >> appium-test-report.md
          echo "3. **Create Task**: Task creation functionality" >> appium-test-report.md
          echo "4. **External Sync**: External document sync verification" >> appium-test-report.md

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: expo-appium-test-results
          path: |
            react-native-expo/android/app/build/outputs/apk/debug/app-debug.apk
            appium-test-report.md
            .github/scripts/browserstack-appium-test.py