name: Swift CI Test

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-swift:
    runs-on: macos-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Swift workflow trigger
      run: |
        echo "✅ Swift CI Test workflow triggered successfully!"
        echo "This proves workflow triggering works with clean configuration"
        ls swift/