name: Test Build Info Action

on:
  workflow_dispatch:

jobs:
  test-build-info:
    name: Test Build Info Generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build info action
        id: build-info
        uses: ./.github/actions/get-browserstack-build-info
        with:
          project-name: 'quickstart - Test Project'
          platform-suffix: ' (Test Platform)'

      - name: Display outputs
        run: |
          echo "## 🧪 Build Info Action Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Outputs:" >> $GITHUB_STEP_SUMMARY
          echo "- **Project Name:** \`${{ steps.build-info.outputs.project-name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Name:** \`${{ steps.build-info.outputs.build-name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Number:** \`${{ steps.build-info.outputs.pr-number }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **PR Title:** \`${{ steps.build-info.outputs.pr-title }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Context Info:" >> $GITHUB_STEP_SUMMARY
          echo "- **Event Name:** \`${{ github.event_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Head Ref:** \`${{ github.head_ref }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Ref Name:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Run Number:** \`${{ github.run_number }}\`" >> $GITHUB_STEP_SUMMARY

          echo ""
          echo "✅ If you see 'PR-XXX: <PR Title>' in Build Name above, the action is working!"
          echo "❌ If you see 'Build-XXX', the PR fetch failed (expected for workflow_dispatch on branch)"
